spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-only

jwt:
  access-duration: ${JWT_DURATION}
  refresh-duration: ${JWT_REFRESH_DURATION}
  secret: ${JWT_SECRET}
